### ISSUE TITLE
Pulling module from registry.opentofu 

### ISSUE THREAD

**Issue by chris-mcclure-array** [alpine-docker/terragrunt#36]
We use this base image of latest for our terragrunt CI and CD.  In the last day or two, it started pull all our modules from registry.opentofu.org instead of hashicorp.  I'm still investigating in our code incase it's on our end somewhere. But we haven't made any code changes to our repo in since last week.

Also it looks like we updated our build in the last 2 days.   I am going to pull an older version of the image to test, but any insight would be helpful. Thanks! 

- Installing registry.opentofu.org/hashicorp/random v3.6.2...
- Installed registry.opentofu.org/hashicorp/random v3.6.2 (self-signed, key ID 
0C0AF313E5FD9F80

**Comment by ozbillwang** [comment]
This is the worst case I've encountered so far.

It relates to the incident described in #34 . After receiving the report, I rolled back the changes (including replacing the tag 1.8.4 image back), but it seems it was too late. Some clients, like you, had already implemented the change with OpenTofu without noticing this issue.

I understand that the fix is challenging. There is no automated way to resolve it; it must be handled manually.
